// Regenerates supabase/seed.sql from public/assets/platform/stations.js
import {writeFile} from 'node:fs/promises';
import {STATIONS} from '../public/assets/platform/stations.js';
const q=s=>s==null?'null':`'${String(s).replace(/'/g,"''")}'`;
const rows=STATIONS.map(s=>`  (${q(s.id)}, ${q(s.system)}, ${q(s.line)}, ${q(s.name)}, ${s.seq}, ${s.x?q('X'+s.x):'null'})`).join(',\n');
const sql=`-- HireMeow seed data. Run after schema.sql (Supabase → SQL Editor).
-- Generated by \`npm run seed:sql\` from public/assets/platform/stations.js.

insert into public.transit_stations (id, system, line, name, seq, interchange_key) values
${rows}
on conflict (id) do update set system = excluded.system, line = excluded.line, name = excluded.name,
  seq = excluded.seq, interchange_key = excluded.interchange_key;
`;
await writeFile(new URL('../supabase/seed.sql',import.meta.url),sql);
console.log('Wrote supabase/seed.sql with',STATIONS.length,'stations');
